### ISSUE TITLE
[Feature] : 이메일 중복확인 API 구현 

### ISSUE THREAD

**Issue by maong0927** [boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-Server#15]
### Summary
회원가입시 입력된 이메일을 중복확인 한다. 

### Additional Context
DB의 기존 유저 정보와 비교하여 이메일을 중복확인 한다.

**Comment by minbert** [comment]
중복확인 후 response로 에러를 전송해야 합니다..!
